### PR TITLE
Wrap mode setting

### PR DESCRIPTION
**Pull request by wellef**
Add support for wrap mode setting for the editor. As a result the editors textarea is now able to flick in both directions when needed.

Also includes a small python bugfix where settings.setDataPath would try to create the directories even when only the conf-file was missing. This was causing an error.

### CODE REVIEW

**Comment by eekkelund** [comment]
Hi @wellef!:)

Thanks a lot for pull requests!:) I am on vacation now I will check them when I get back home on January. (I checked them really quickly, looked good!:) )

**Comment by wellef** [comment]
I stumbled across an issue in settings.py that this pull request is affected by.
There is no default values for the settings, which means that if you installed an older version of the app there is no way to include newly added settings (like wrapmode). This also happens if you remove a setting from the conf-file.

I suggest something like this:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pyotherside
import configparser
import os

dataPath = None
defaults = {
    'customtheme': 'False',
    'fontsize': '35',
    'fonttype': "Sail Sans Pro Light",
    'linenums': 'True',
    'autosave': 'True',
    'indentsize': '4',
    'textcolor':"#cfbfad",
    'qmlcolor':"#ff8bff",
    'keycolor':"#808bed",
    'propertiescolor':"#ff5555",
    'jscolor':"#8888ff",
    'strcolor':"#ffcd8b",
    'commentcolor':"#cd8b00",
    'bgcolor':"#1e1e27",
    'trace':'False',
    'hint':'0',
    'plugins':'False',
    'wrapmode': 3
}

def setDataPath(path):
    confPath = path+"/harbour-tide.conf"
    if not os.path.exists(confPath):
        os.makedirs(path)
        config = configparser.RawConfigParser()
        config['editor'] = defaults
        with open(confPath, 'a+') as cfg:
            config.write(cfg)
    global dataPath
    dataPath = confPath
    return "path added"


def set(key, value):
    config = configparser.RawConfigParser()
    if(dataPath!=None):
        #Updating configuration file '.conf'
        config.read(dataPath)
        config.set('editor', key, value)
        with open(dataPath, 'w+') as configfile:
            config.write(configfile)

def get(key):
    config = configparser.RawConfigParser()
    if(dataPath!=None):
        config.read(dataPath)
        try:
            result = config['editor'][key]
        except:
            if hasattr(defaults, key):
                result = defaults.key
            else
                print("Warning: The provided key is not in the config yet, saving it just in case")
                set(key, 0)
                result = 0
                
        return result
```

**Comment by eekkelund** [comment]
Haha, you don't believe:D I just ½h ago checked this your pull request and added same kind of solution! :)
```
dataPath=None
editorDefaults={'darktheme': 'True',
'fontsize': '35',
'fonttype': "Sail Sans Pro Light",
'linenums': 'True',
'autosave': 'True',
'indentsize': '4',
'textcolor':"#cfbfad",
'qmlcolor':"#ff8bff",
'keycolor':"#808bed",
'propertiescolor':"#ff5555",
'jscolor':"#8888ff",
'strcolor':"#ffcd8b",
'commentcolor':"#cd8b00",
'bgcolor':"#1e1e27",
'trace':'False',
'hint':'0',
'plugins':'False',
'wrapmode': 3
}

def setDataPath(path):
    confPath = path+"/harbour-tide.conf"
    if not os.path.exists(path):
        os.makedirs(path)
    if not os.path.exists(confPath):
        config = configparser.RawConfigParser()
        config['editor']=editorDefaults
        with open(confPath, 'a+') as cfg:
            config.write(cfg)
    global dataPath
    dataPath = confPath
    return "path added"


def set(key, value):
    config = configparser.RawConfigParser()
    if(dataPath!=None):
        #Updating configuration file '.conf'
        config.read(dataPath)
        config.set('editor', key, value)
        with open(dataPath, 'w+') as configfile:
            config.write(configfile)

def get(key):
    config = configparser.RawConfigParser(defaults = editorDefaults)
    if(dataPath!=None):
        config.read(dataPath)
        if not config.has_option('editor',key):
            config.set('editor', key, default)
        result = config['editor'][key]
        return result
```

**Comment by eekkelund** [comment]
Hmm, I think I f*cked up something.. I merged your pull requests locally and pushed them but these didn't close.. o.O
Well I will close this manually and hopefully learned something new about Git. Thanks for your contribution! I would happy to have more pull requests or/and suggestions :)

**Pull request closed without merging**
